package com.bank.islamic.commoditymurabahatawarruq;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Commodity Murabaha Tawarruq
 *
 * Business Area:      Islamic Financing
 * Business Domain:    Sale Based Financing
 * Functional Pattern: Process
 * Asset Type:         Tawarruq Transaction
 * Control Record:     Tawarruq Transaction Procedure
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Commodity Murabaha Tawarruq — BIAN Semantic API")
                .description("Service Domain 'Commodity Murabaha Tawarruq' (Process pattern) "
                        + "operating on the 'Tawarruq Transaction Procedure' control record.")
                .version("0.1.0"));
    }
}
